### PR TITLE
add proxy support to connection

### PR DESCRIPTION
**Pull request by jsmolina**
Sometimes your host needs to jump a host to reach internet. 

This change adds support for proxy in libary in the simplest way as HTTP20Connection already supports the proxy param.

### CODE REVIEW

**Comment by jsmolina** [comment]
@Pr0Ger ?

**Comment by Pr0Ger** [comment]
Yea, sorry it took so long to review this PR. I think it's better to pass these params directly to `Credentials.create_connection` method instead of saving them inside `Credentials` constructor (same way how `force_proto` param is handled).

**Comment by jsmolina** [comment]
agree with you, changed so @Pr0Ger

**Comment by Pr0Ger** [comment]
@jsmolina thx for contribution

**Pull request merged**
