### PR TITLE
Send custom payload without subclassing apns2.Payload

### PR DESCRIPTION
**Pull request by Yannic**

### CODE REVIEW

**Comment by Pr0Ger** [comment]
Hi!

Sorry for long response, I appreciate your work, but this functionality is already available in current version.
For example, if we want to send push about successful order and send order id to user device:
```
In [1]: from apns2.payload import Payload

In [2]: payload = Payload(alert="Your order has been shipped", badge=1, custom={"type": "order_shipped", "order_id": 123})

In [3]: payload.dict()
Out[4]:
{'aps': {'alert': 'Your order has been shipped', 'badge': 1},
 'order_id': 123,
 'type': 'order_shipped'}
```
Is this what you are trying to achieve?

**Comment by YannicBonenberger** [comment]
My goal is to send Safari Push Notifications.
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html#//apple_ref/doc/uid/TP40013225-CH3-SW1

Is there a way to achieve this more efficient than this?
```python
pl = {
    "aps": {
        "alert": {
            "title": "Flight A998 Now Boarding",
            "body": "Boarding has begun for Flight A998.",
            "action": "View"
        },
        "url-args": ["boarding", "A998"]
    }
}

payload = Payload(custom=pl)
```

**Comment by Pr0Ger** [comment]
This library is initially intended for iOS related pushes where action button can be customized via `action-loc-key` key, it's the reason why `PayloadAlert` doesn't have `action` property. Also, iOS pushes don't have `url-args` key.

As far as I see it's the only changes required to support Safari Push Notifications. I just pushed support for it in master branch:
```
In [1]: from apns2.payload import Payload, PayloadAlert

In [2]: payload_alert = PayloadAlert(title="Flight A998 Now Boarding", body="Boarding has begun for Flight A998.", action="View")

In [3]: payload = Payload(alert=payload_alert, url_args=["boarding", "A998"])

In [4]: payload.dict()
Out[4]:
{'aps': {'alert': {'action': 'View',
   'body': 'Boarding has begun for Flight A998.',
   'title': 'Flight A998 Now Boarding'},
  'url-args': ['boarding', 'A998']}}
```

**Comment by Pr0Ger** [comment]
Support for Safari Push Notifications is available in 0.2.0 version (now available in PyPI), so I'm closing this

**Pull request closed without merging**
