### PR TITLE
Some changes in client.py for hyper v0.6.0

### PR DESCRIPTION
**Pull request by firkeuf**
hyper > common > util > to_bytestring
can not convert INT to byte
and raise ValueError("Non string type.")

------------------

should add force_proto else get proto = None and crash

hyper/http20/connection.py", line 354
assert proto in H2_NPN_PROTOCOLS or proto == H2C_PROTOCOL

### CODE REVIEW

**Comment by leovp** [comment]
I guess it's time to write some tests and documentation.
Will definitely help with that.
@Pr0Ger

**Comment by Pr0Ger** [comment]
I'll definitely merge first change, I was busy when new version of hyper was released.

But can I have some details about second change? I've tried to reproduce it, but everything works fine for me (Python 2.7.11/3.5.1 and hyper 0.6.0). Looks like it is related to this issue Lukasa/hyper#197, am I right?

**Comment by firkeuf** [comment]
Yes its related https://github.com/Lukasa/hyper/pull/197.
on fresh Centos 6.7 and Python 3.5.1

```
from apns2.client import APNsClient
from apns2.payload import Payload

token_hex = '***'
payload = Payload(content_available=True)
client = APNsClient('apns-dev-cert.pem', use_sandbox=False)
client.send_notification(token_hex, payload)
```

```
Traceback (most recent call last):
  File "/home/fir/devel/ami2apec/qqqtest.py", line 7, in <module>
    client.send_notification(token_hex, payload)
  File "/home/fir/devel/virtualenvs/ami2apec/lib/python3.5/site-packages/apns2/client.py", line 34, in send_notification
    stream_id = self.__connection.request('POST', url, json_payload, headers)
  File "/home/fir/devel/virtualenvs/ami2apec/lib/python3.5/site-packages/hyper/http20/connection.py", line 262, in request
    self.endheaders(message_body=body, final=True, stream_id=stream_id)
  File "/home/fir/devel/virtualenvs/ami2apec/lib/python3.5/site-packages/hyper/http20/connection.py", line 525, in endheaders
    self.connect()
  File "/home/fir/devel/virtualenvs/ami2apec/lib/python3.5/site-packages/hyper/http20/connection.py", line 354, in connect
    assert proto in H2_NPN_PROTOCOLS or proto == H2C_PROTOCOL
AssertionError
```

 I have assertion 
```
# proto = None
assert proto in H2_NPN_PROTOCOLS or proto == H2C_PROTOCOL
```
```
$pip freeze
apns2==0.1.0
h2==2.3.1
hpack==2.2.0
hyper==0.6.0
hyperframe==3.2.0
```

**Comment by Pr0Ger** [comment]
I'm sorry that it takes so long to merge your pull request, I'm really bad with finding free time in last month.

I also published updated version to PyPi.

**Pull request merged**
